name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ contains(github.event.comment.body, '/fast-forward')
            && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fast forwarding
        uses: smartin-vossloh/fast-forward@9bacd3aa8db95ad80a71ed02f1f2409d245f0b78
        with:
          merge: true
          merge-method: merge-commit
          merge-author: triggerer
          merge-user-name: 'fast-forward[bot]'
          merge-user-email: 'fast-forward[bot]@users.noreply.github.com'
          # To reduce the workflow's verbosity, use 'on-error'
          # to only post a comment when an error occurs, or 'never' to
          # never post a comment.  (In all cases the information is
          # still available in the step's summary.)
          comment: always
